#Enable changing skins of players on join
JoinSkins: true
#Skins need to be base64 encoded!
#Username of the server owner
Owner: SalmonDE
#Check if skin could be changed on join
CheckJoinSkin: true
#Time in seconds when the check should begin
SkinCheckTime: 20
